version: '3'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: shortlinks
      POSTGRES_USER: nnn
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432" 
    restart: always

  postgres-test:
    image: postgres:13
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5433:5432

  web:
    restart: always
    build: .
    volumes:
      - ./:/code:ro
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:${PORT}/${POSTGRES_DB}
    ports:
      - "8000:80"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data: